### ISSUE TITLE
'vuepress build' cannot find vue-good-table styles

### ISSUE THREAD

**Issue by chbndrhnns** [FriendlyUser/vuepress-theme-cool#3]
I can use the `vuepress dev .` command and see my docs in the browser. However, when I run `vuepress build .`, I receive the following error:

```
  WAIT  Rendering static HTML...
Rendering page: /how-to/ FAIL  Error rendering /how-to/:
Error: Cannot find module 'vue-good-table/dist/vue-good-table.css?vue&type=style&index=0&lang=css&'
    at Function.Module._resolveFilename (module.js:547:15)
    at Function.Module._load (module.js:474:25)
    at Module.require (module.js:596:17)
    at require (internal/module.js:11:18)
    at r (/Users/jo/.config/yarn/global/node_modules/vue-server-renderer/build.js:8346:16)
    at Object.<anonymous> (webpack:/external "vue-good-table/dist/vue-good-table.css:1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at VueComponent.injectStyles (.vuepress/components/demo-table.vue:6:0)
    at VueComponent.hook (Users/jo/.config/yarn/global/node_modules/vuepress/node_modules/vue-loader/lib/runtime/componentNormalizer.js:53:0)
    at callHook (/Users/jo/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:2919:21)
    at VueComponent.Vue._init (/Users/jo/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:4624:5)
    at new VueComponent (/Users/jo/.config/yarn/global/node_modules/vue/dist/vue.runtime.common.js:4796:12)
    at createComponentInstanceForVnode (/Users/jo/.config/yarn/global/node_modules/vue-server-renderer/build.js:7353:10)
    at renderComponentInner (/Users/jo/.config/yarn/global/node_modules/vue-server-renderer/build.js:7527:40)
    at renderComponent (/Users/jo/.config/yarn/global/node_modules/vue-server-renderer/build.js:7502:5)
    at resolve (/Users/jo/.config/yarn/global/node_modules/vue-server-renderer/build.js:7563:9)
 ⚙
```

I need to comment the <style> section in the table component to make it work. How do I need to provide the path to the style sheet so that the build process works?

**Comment by FriendlyUser** [comment]
I'll look into this issue.

**Comment by FriendlyUser** [comment]
See https://vuepress-examples.netlify.com, they explain how to include packaged css
