### ISSUE TITLE
Update Theme for Vuepress 1.0.0

### ISSUE THREAD

**Issue by FriendlyUser** [FriendlyUser/vuepress-theme-cool#4]
Update the theme to vuepress 1.0.0 as soon as it is released in order to add blogging, etc ...

**Comment by chbndrhnns** [comment]
Now it has been released :)

**Comment by chbndrhnns** [comment]
Is the README already updated for the modifications for vuepress v1? I am following your instructions and I currently receive this error message:

```
> @ docs:dev /Users/powerjo/dev/scratch/vuepress-1
> vuepress dev docs

wait Extracting site metadata...
Error: Cannot resolve theme: cool.
    at resolveTheme (/Users/powerjo/dev/scratch/vuepress-1/node_modules/@vuepress/core/lib/node/loadTheme.js:109:13)
    at loadTheme (/Users/powerjo/dev/scratch/vuepress-1/node_modules/@vuepress/core/lib/node/loadTheme.js:35:17)
    at App.process (/Users/powerjo/dev/scratch/vuepress-1/node_modules/@vuepress/core/lib/node/App.js:100:21)
    at dev (/Users/powerjo/dev/scratch/vuepress-1/node_modules/@vuepress/core/lib/index.js:14:13)
    at args (/Users/powerjo/dev/scratch/vuepress-1/node_modules/vuepress/lib/util.js:35:12)
    at CAC.cli.command.option.option.option.option.option.option.option.option.option.action (/Users/powerjo/dev/scratch/vuepress-1/node_modules/vuepress/lib/registerCoreCommands.js:38:23)
    at CAC.runMatchedCommand (/Users/powerjo/dev/scratch/vuepress-1/node_modules/cac/dist/index.js:700:38)
    at CAC.parse (/Users/powerjo/dev/scratch/vuepress-1/node_modules/cac/dist/index.js:620:18)
    at CLI (/Users/powerjo/dev/scratch/vuepress-1/node_modules/vuepress/lib/util.js:23:7)
    at process._tickCallback (internal/process/next_tick.js:68:7)
n
```

**Comment by FriendlyUser** [comment]
Yes it is, you may need to update your version of vuepress, seems to work with vuepress @1.0.2. I forgot to mention that for the beta version you would need to install the beta version of the theme. yarn install -D vuepress-theme-cool@1.0.3-beta



Sounds related to the issue indicated at https://github.com/vuejs/vuepress/issues/1568

See 
https://travis-ci.org/FriendlyUser/vuepress-theme-cool-starter/jobs/561507711 for a working build.

And https://github.com/FriendlyUser/vuepress-theme-cool-starter is updated as well, will update documentation shortly.
