### ISSUE TITLE
Vue good table is causing error on build

### ISSUE THREAD

**Issue by gabrielsclimaco** [FriendlyUser/vuepress-theme-cool#7]
whenever I try the command `vuepress build docs` (local not global) I get the following error:

```
Rendering static HTML...
Rendering page: / FAIL  Error rendering /:
ReferenceError: document is not defined
    at Object.<anonymous> (/home/climaco/program/labute/documentation/node_modules/vue-good-table/dist/vue-good-table.cjs.js:2300:12)
    at Module._compile (internal/modules/cjs/loader.js:654:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:665:10)
    at Module.load (internal/modules/cjs/loader.js:566:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:506:12)
    at Function.Module._load (internal/modules/cjs/loader.js:498:3)
    at Module.require (internal/modules/cjs/loader.js:598:17)
    at require (internal/modules/cjs/helpers.js:11:18)
    at /home/climaco/program/labute/documentation/node_modules/vue-server-renderer/build.prod.js:1:77439
    at Object.<anonymous> (webpack:/external "vue-good-table":1:0)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Module.<anonymous> (server-bundle.js:38492:32)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at Object.<anonymous> (server-bundle.js:25292:18)
    at __webpack_require__ (webpack/bootstrap:25:0)
    at server-bundle.js:118:18

```

**Comment by FriendlyUser** [comment]
Could be related to, https://github.com/FriendlyUser/vuepress-theme-cool-starter/issues/1.

May end up removing `vue-good-table` and only use it for the starter repo for components. 

I'll be updating this repo soon and make sure the build works.

What version of vue good table are you using
